# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "creuch_workspace"
client_id = "d612b4cff032e7c9374665cb02060548"
application_url = "https://decorative-quarterly-officials-spouse.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://decorative-quarterly-officials-spouse.trycloudflare.com/auth/callback",
  "https://decorative-quarterly-officials-spouse.trycloudflare.com/auth/shopify/callback",
  "https://decorative-quarterly-officials-spouse.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "creuch-shop.myshopify.com"
