# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Admin Creuch"
client_id = "09be7311801190a8dfa85501d6178bef"
application_url = "https://digit-qualified-choose-gathered.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://digit-qualified-choose-gathered.trycloudflare.com/auth/callback",
  "https://digit-qualified-choose-gathered.trycloudflare.com/auth/shopify/callback",
  "https://digit-qualified-choose-gathered.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "creuch-shop.myshopify.com"
